

export const destinations = [

    { nombre: 'Acapulco / Barra vieja', kms: 300 },
    { nombre: 'Taxco', kms: 300 },
    { nombre: 'Zoofari', kms: 350 },
    { nombre: 'Tepoztlan', kms: 450 },
    { nombre: 'Puerto vicente', kms: 500 },
    { nombre: 'Hacienda panoaya', kms: 550 },
    { nombre: 'CDMX', kms: 550 },
    { nombre: 'Puebla', kms: 600 },
    { nombre: 'Villa iluminada', kms: 600 },
    { nombre: 'Valquirico', kms: 650 },
    { nombre: 'Teotihuacan', kms: 650 },
    { nombre: 'Luciernagas', kms: 700 },
    { nombre: 'Nevado', kms: 750 },
    { nombre: 'Volcanic park', kms: 800 },
    { nombre: 'Bioparque', kms: 800 },
    { nombre: 'Chignahuapan y Zacatlan', kms: 850 },
    { nombre: 'Monarcas / valle de bravo', kms: 900 },
    { nombre: 'Tlalpujahua / El oro', kms: 900 },
    { nombre: 'Cuetzalan y tlatlauquitepec', kms: 1000 },
    { nombre: 'Geiser', kms: 1000 },
    { nombre: 'Tolantongo', kms: 1000 },
    { nombre: 'Queretaro / bernal', kms: 1050 },
    { nombre: 'Viñedos', kms: 1100 },
    { nombre: 'Veracruz', kms: 1200 },
    { nombre: 'Juquila y pto', kms: 1200 },
    { nombre: 'Ecoturismo Qro', kms: 1300 },
    { nombre: 'Morelia y patzcuaro', kms: 1300 },
    { nombre: 'Guanajuato y sillao o Allende', kms: 1300 },
    { nombre: 'Leon y Gto', kms: 1400 },
    { nombre: 'Oaxaca', kms: 1400 },
    { nombre: 'Zacatecas', kms: 2000 },
    { nombre: 'Huasteca', kms: 2200 },
    { nombre: 'Mty', kms: 2400 },
    
];